### ISSUE TITLE
Board Tic-tac-toe border style

### ISSUE THREAD

**Issue by djoshuac** [djoshuac/tic-tac-toe-inception#2]
Set up the board to look like tic-tac-toe inception

**Comment by stimothy** [comment]
Ok, the CSS for the board is pretty much set up, there was one change from the last time we talked. If you look at the id's/classes, there was one more that I needed to add to make it easier to separate the mini-games from the big game. So I gave all of the little tables the class "miniGame".

**Comment by djoshuac** [comment]
**Awesome, Looking great!**

Maybe some future styling ideas:

- center the cell's text
- center the tac games
- ensure that the cells in the toe game are square

**Comment by stimothy** [comment]
Ok sounds like a plan. I should have all those fixed by tonight, as for centering the tac games. I am not sure that I can center those and still keep a margin. I will look into that, but once all of the sizes are set, they should be "centered".
